### ISSUE TITLE
Verifying account ownership in group transaction broken

### ISSUE THREAD

**Issue by k13n** [blockshake-io/account_abstraction#1]
Function `verifyRekeyToAbstractedAccount` is used to verify that by the end of a transaction group the account is controlled by the smart contract and should fail if that's not the case. It looks like this check isn't working properly right now, which means flash rekeying isn't guaranteed to work.

Function `verifyRekeyToAbstractedAccount` looks for a transaction in the group that either rekeys the controlled account back to the app or for a call to `arc58_verifyAuthAddr`. In either case `getAuthAddr` is called which returns the expected auth-addr for the abstracted account. Assuming that the controlled account is the app account (`this.controlledAddress.value === this.app.address`), `getAuthAddr` returns the zero-address. The problem occurs in the following lines in `verifyRekeyToAbstractedAccount`:

```ts
// The transaction is an explicit rekey back
if (txn.sender === this.controlledAddress.value && txn.rekeyTo === this.getAuthAddr()) {
  rekeyedBack = true;
  break;
}
```

If the group contains, e.g., a payment from the controlled address to some other address **without** explicit rekeying, this statement evaluates to true and `verifyRekeyToAbstractedAccount` succeeds. This is because `txn.rekeyTo === Address.zeroAddress` since the transaction doesn't contain an explicit rekeying and the default value for that field is the zero-address. As a result, the app thinks it has control over the controlled account, but in fact hasn't.

Function `arc58_verifyAuthAddr` looks fine:

```ts
arc58_verifyAuthAddr(): void {
    assert(this.controlledAddress.value.authAddr === this.getAuthAddr());
}
```

I think the reason why `arc58_verifyAuthAddr` is okay is because it looks for an *effect* (auth-addr is cleared to zero-address), while the first code block looks for an *action* (rekey field is zero).

One possible solution is to only check for `arc58_verifyAuthAddr`, but this means we necessarily have to add that transaction to the group, while the other approach doesn't require that.

**Comment by kylebeee** [comment]
Im fine with just removing it & forcing any flash rekeys to tack on a `arc58_verifyAuthAddr` call. The initial thought was "it would be nice if that extra call wasn't necessary if thy combine the rekey back with some other txn they're doing" but clearly it doesn't work well. It has other issues as well, eg. This only checks the outer group, which means even if a plugin rekeys back using an itxn `arc58_verifyAuthAddr` still has to be called.

**Comment by k13n** [comment]
I'm closing this issue here and re-opening it in the original repository [here](https://github.com/joe-p/account_abstraction/issues/6).
